### ISSUE TITLE
query with datetime range

### ISSUE THREAD

**Issue by panicpotatoe** [rouanw/mongo-csv#1]
I'm trying to write a datetime range in query such like this
`
{
  "url": "mongodb://localhost:27017",
  "databaseName": "mydb",
  "authDb": "admin",
  "collection": "cols",
  "query": {
		"Date": {
			"$gte": ISODate("2018-12-31T00:00:00.000Z"),
			"$lte": ISODate("2019-01-30T00:00:00.000Z")
		}
	}
}
`
but **it keeps getting error "config.json: Unexpected token I in JSON at position 297"**
I'm not sure the core problem or my code wrong... Could you please check

And by the way, **is there any option for limit() function?**

**Comment by rouanw** [comment]
Hi @panicpotatoe! Thanks for your question. `mongo-csv` wasn't handling dates, which is part of why your query wasn't working. I've released `mongo-csv@1.1.0` which should fix that. You'll also need to adjust your JSON as it's not currently valid. Will you please try:

```sh
npm install mongo-csv@1.1.0
```

and adjust your JSON to something like:

```json
{
  "url": "mongodb://localhost:27017",
  "databaseName": "mydb",
  "authDb": "admin",
  "collection": "cols",
  "query": {
    "Date": { "$gte": "2018-12-31T00:00:00.000Z", "$lte": "2019-01-30T00:00:00.000Z" }
  }
}
```

In other words, remove the `ISODate` wrappers and quote `$gte` and `$lte`.

Please let me know if that works 😄

**Comment by rouanw** [comment]
@panicpotatoe I just saw your update - I'll look into supporting `limit` - it doesn't at the moment.

**Comment by rouanw** [comment]
@panicpotatoe I've made a small (breaking) change to the library to support `limit` (along with any other of the [Mongo `find` options](http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#find)).

Try `mongo-csv@2.0.0` and specify your limit like:

```json
  // rest of config.json
  "options": { "limit": 10 }
```

(It's a breaking change because the library now expects `projection` as part of the `options` property.)

**Comment by panicpotatoe** [comment]
@rouanw yay, that's great! I tried @1.1.0 and it works like a charm. Thank you so much. You're the best ^^
